name: 'Arch Linux User Repository (AUR) GitHub Action'
description: ''
author: 'JamieMagee'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  pkgname:
    description: ''
    required: true

runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.pkgname }}
