name: Update Package

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master

jobs:
  update_package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Find updated package
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          echo "pkgbuild=$(git diff --name-only origin/master origin/${GITHUB_HEAD_REF} "*PKGBUILD" | head -1 | xargs dirname)" >> $GITHUB_ENV

      - name: Cache packages and bazel builds
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
        if: ${{ env.pkgbuild != '' }}
        with:
          path: .cache
          key: ${{ runner.os }}-${{ env.pkgbuild }}-paru-bazel

      - name: Run update script
        if: ${{ env.pkgbuild != '' }}
        run: |
          /bin/bash .github/renovate-onupdate.sh

      - name: Validate package
        if: ${{ env.pkgbuild != '' }}
        uses: ./.github/actions/aur
        with:
          pkgname: ${{ env.pkgbuild }}

      - name: Commit
        if: ${{ env.pkgbuild != '' }}
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
