name: Update Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  update_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Find updated package
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          echo "pkgbuild=$(git diff --name-only origin/master origin/${GITHUB_HEAD_REF} "*PKGBUILD" | head -1 | xargs dirname)" >> $GITHUB_ENV

      - name: Cache packages and bazel builds
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        if: ${{ env.pkgbuild != '' }}
        with:
          path: .cache
          key: ${{ runner.os }}-${{ env.pkgbuild }}-paru-bazel

      - name: Validate package
        if: ${{ env.pkgbuild != '' }}
        uses: ./.github/actions/verify
        with:
          pkgname: ${{ env.pkgbuild }}
